import {
  CustomerRequest,
  DashboardStats,
  InventoryItem,
  PurchaseRecommendation,
  SalesTrendPoint,
  StoreLog,
} from "./ownerIntelligenceTypes";

export const initialOwnerInventory: InventoryItem[] = [
  {
    id: "LP-9012",
    artist: "Fleetwood Mac",
    title: "Rumours",
    format: "LP",
    genre: "Classic Rock",
    status: "Critical",
    inStock: 1,
    reserved: 2,
    price: 34.99,
    releaseYear: 1977,
    notes: "High demand, persistent classic. Hard to keep on the shelves.",
  },
  {
    id: "LP-1023",
    artist: "Madvillain",
    title: "Madvillainy",
    format: "LP",
    genre: "Hip Hop",
    status: "Trending",
    inStock: 12,
    reserved: 2,
    price: 34.99,
    releaseYear: 2004,
    notes: "Substantial interest among collegiate regulars.",
  },
  {
    id: "BK-4421",
    artist: "John Berger",
    title: "Ways of Seeing",
    format: "BOOK",
    genre: "Art Theory",
    status: "Warning",
    inStock: 2,
    reserved: 0,
    price: 18,
    releaseYear: 1972,
    notes: "Classic critical visual theory. Frequently assigned in local courses.",
  },
  {
    id: "LP-7762",
    artist: "Alice Coltrane",
    title: "Journey in Satchidananda",
    format: "LP",
    genre: "Spiritual Jazz",
    status: "Restocked",
    inStock: 28,
    reserved: 1,
    price: 29.99,
    releaseYear: 1971,
    notes: "Essential avant-garde. Frequent request on customer slips.",
  },
  {
    id: "LP-0001",
    artist: "Miles Davis",
    title: "Kind of Blue",
    format: "LP",
    genre: "Jazz",
    status: "Trending",
    inStock: 15,
    reserved: 3,
    price: 34.99,
    releaseYear: 1959,
    notes: "The highest-selling jazz record of all time. Core catalog title.",
  },
  {
    id: "BK-2034",
    artist: "Joan Didion",
    title: "The White Album",
    format: "BOOK",
    genre: "Essays",
    status: "Steady",
    inStock: 4,
    reserved: 0,
    price: 18,
    releaseYear: 1979,
    notes: "Literary classic. Strong record-store/bookshop bridge item.",
  },
];

export const initialCustomerRequests: CustomerRequest[] = [
  {
    id: "REQ-001",
    date: "2026-06-08",
    patronName: "Evelyn Finch",
    artist: "Sun Ra",
    title: "Space Is The Place",
    format: "LP",
    notes: "Looking for an original, or El Saturn repress. Thinks we need more space-age avant-garde jazz on shelves.",
    source: "In-store Slip",
    quantity: 1,
    genre: "Avant-Garde Jazz",
  },
  {
    id: "REQ-002",
    date: "2026-06-09",
    patronName: "Liam Cole",
    artist: "William Gibson",
    title: "Neuromancer",
    format: "BOOK",
    notes: "Wants classic hardback or elegant reprint. Several customers have asked about cyberpunk fiction.",
    source: "Web Concierge",
    quantity: 2,
    genre: "Fiction",
  },
  {
    id: "REQ-003",
    date: "2026-06-09",
    patronName: "Clara Vance",
    artist: "Aphex Twin",
    title: "Selected Ambient Works 85-92",
    format: "LP",
    notes: "Warp reissue preferred. Four separate patrons asked this past week.",
    source: "Web Concierge",
    quantity: 5,
    genre: "Electronic",
  },
  {
    id: "REQ-004",
    date: "2026-06-07",
    patronName: "Marcus Reed",
    artist: "Virginia Woolf",
    title: "To the Lighthouse",
    format: "BOOK",
    notes: "Uniform edition or Hogarth Press styled reprint. High literary request.",
    source: "In-store Slip",
    quantity: 2,
    genre: "Fiction",
  },
];

export const initialOwnerRecommendations: PurchaseRecommendation[] = [
  {
    id: "REC-SEED-01",
    artist: "Fleetwood Mac",
    title: "Rumours",
    genre: "Classic Rock",
    format: "LP",
    action: "Order 15 units immediately",
    reason: "Core catalog title is down to 1 on-hand with 2 reserved. This is a safe, high-velocity asset for an independent record shop.",
    confidenceScore: 98,
    sampleSizeWarning: "High significance: rooted in repeated inventory turns and steady multi-season sales behavior.",
    sampleSizeSignificant: "High",
    requestVolume: 12,
    trendSignalQuality: "Strong",
    estCost: 18.5,
    estRetail: 34.99,
  },
  {
    id: "REC-SEED-02",
    artist: "Aphex Twin",
    title: "Selected Ambient Works 85-92",
    genre: "Electronic / Ambient",
    format: "LP",
    action: "Buy 10 units via distributor",
    reason: "Supported by recent digital requests and a visible ambient/electronic signal among regulars. Watch for trend-spike risk before over-ordering.",
    confidenceScore: 89,
    sampleSizeWarning: "Medium significance: strong recent interest, but still based on a small web request sample.",
    sampleSizeSignificant: "Medium",
    requestVolume: 5,
    trendSignalQuality: "Strong",
    estCost: 16,
    estRetail: 29.99,
  },
  {
    id: "REC-SEED-03",
    artist: "Sun Ra",
    title: "Space Is The Place",
    genre: "Avant-Garde Jazz",
    format: "LP",
    action: "Source 2 high-quality used copies",
    reason: "A strong brand-authenticity title, but the current signal is a single patron request. Keep first-buy count sparse to protect cash reserves.",
    confidenceScore: 68,
    sampleSizeWarning: "Low significance: based on one floor request. Human review recommended before stocking deeply.",
    sampleSizeSignificant: "Low",
    requestVolume: 1,
    trendSignalQuality: "Weak",
    estCost: 14,
    estRetail: 28,
  },
];

export const ownerDashboardStats: DashboardStats = {
  totalRevenue: 42890,
  revenueChangePct: 12.5,
  activePatrons: 1204,
  patronsChangeCount: 48,
  vinylUnitsCount: 1240,
  bookUnitsCount: 840,
  sellThruRate: 94,
  avgTicket: 142,
};

export const ownerSalesTrends: SalesTrendPoint[] = [
  { month: "Jan", sales: 160, listening: 180 },
  { month: "Feb", sales: 140, listening: 150 },
  { month: "Mar", sales: 120, listening: 100 },
  { month: "Apr", sales: 90, listening: 110 },
  { month: "May", sales: 140, listening: 130 },
  { month: "Jun", sales: 110, listening: 140 },
  { month: "Jul", sales: 95, listening: 152 },
  { month: "Aug", sales: 135, listening: 120 },
  { month: "Sep", sales: 110, listening: 140 },
  { month: "Oct", sales: 165, listening: 135 },
];

export const initialStoreLogs: StoreLog[] = [
  {
    id: "LOG-001",
    date: "2026-06-08",
    author: "Brandon Carson",
    text: "Check book reservations and keep an eye on core classic rock restocks before the weekend.",
    color: "yellow",
    category: "Operations",
  },
  {
    id: "LOG-002",
    date: "2026-06-09",
    author: "Michelle Lentz",
    text: "Week 3 testing exposed the big risk: request volume can look confident even when intent is fuzzy.",
    color: "kraft",
    category: "General",
  },
];

export function buildOwnerRecommendations(
  inventory: InventoryItem[],
  requests: CustomerRequest[],
  budgetLimit: string,
  riskSetting: string,
): PurchaseRecommendation[] {
  const budgetMultiplier = budgetLimit === "tight" ? 0.6 : budgetLimit === "rich" ? 1.35 : 1;
  const lowStockPlans = inventory
    .filter((item) => item.inStock <= 2)
    .map((item) => {
      const units = Math.max(2, Math.round((item.inStock <= 1 ? 12 : 7) * budgetMultiplier));
      return {
        id: `REC-${item.id}`,
        artist: item.artist,
        title: item.title,
        genre: item.genre,
        format: item.format,
        action: `Order ${units} units from distributor`,
        reason: `${item.title} is under the restock threshold with ${item.inStock} on hand and ${item.reserved} reserved. This is an inventory-protection recommendation, not proof of new demand.`,
        confidenceScore: item.inStock <= 1 ? 94 : 82,
        sampleSizeWarning: "High significance: driven by active stock shortage and reservation pressure.",
        sampleSizeSignificant: "High",
        requestVolume: Math.max(1, item.reserved),
        trendSignalQuality: "Strong",
        estCost: Math.round(item.price * 0.55),
        estRetail: item.price,
      } satisfies PurchaseRecommendation;
    });

  const requestPlans = requests.slice(0, 3).map((request) => {
    const conservative = riskSetting === "conservative";
    return {
      id: `REC-${request.id}`,
      artist: request.artist,
      title: request.title,
      genre: request.genre || "Uncategorized",
      format: request.format,
      action: conservative ? "Source 1-2 copies for human review" : `Order ${Math.max(2, request.quantity * 2)} copies`,
      reason: `${request.source} signal from ${request.patronName}. Treat as demand evidence, but validate against purchase history or repeat requests before a deep buy.`,
      confidenceScore: request.quantity >= 4 ? 74 : 62,
      sampleSizeWarning: "Low to medium significance: request-driven signal. Watch for viral spikes or coordinated requests.",
      sampleSizeSignificant: request.quantity >= 4 ? "Medium" : "Low",
      requestVolume: request.quantity,
      trendSignalQuality: request.quantity >= 4 ? "Moderate" : "Weak",
      estCost: request.format === "BOOK" ? 11 : 16,
      estRetail: request.format === "BOOK" ? 22 : 31.99,
    } satisfies PurchaseRecommendation;
  });

  return [...lowStockPlans, ...requestPlans].slice(0, 6);
}
